### ISSUE TITLE
CHANGE module name in maven pom.xml

### ISSUE THREAD

**Issue by lewismc** [maestros/gora-oraclenosql#1]
Currently the name in the oracle pom.xml clones the one is HBase. This should be changed when you get time.

**Comment by maestros** [comment]
OK, corrected. I am not sure about the following though: 

   < scm >
        < url >http://svn.apache.org/viewvc/gora/trunk/gora-oracle/</ url >
        < connection >scm:svn:http://svn.apache.org/repos/asf/gora/trunk/gora-oracle/</ connection >
        < developerConnection >scm:svn:https://svn.apache.org/repos/asf/gora/trunk/gora-oracle/</ developerConnection >
    </ scm >

**Comment by lewismc** [comment]
Don't worry about this. It will sort itself out later if and when we can publish this module as a stable maven artifact.
Thanks
Lewis
